import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import "./globals.css";
import { Nav } from "@/components/nav/nav";
import { ThemeContextProviders } from "@/context/themeContextWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
            <ThemeContextProviders>
              <Nav />
              <main>{children}</main>
            </ThemeContextProviders>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
