import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import "@/styles/globals.css";
import { Nav } from "@/components/nav/nav";
import { ThemeContextProviders } from "@/context/themeContextWrapper";
import { Footer } from "@/components/footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeContextProviders>
            <Nav />
            <main>{children}</main>
            <Footer />
          </ThemeContextProviders>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
