import { JobDetails } from "@/types";

export const jobOffers: JobDetails[] = [
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Software Engineer II, Chrome",
    companyName: "Google",
    locations: ["Warszawa"],
    salary: {
      isUndisclosed: false,
      from: 20000,
      to: 27000,
      currency: "PLN",
    },
    datePosted: "04/08/2024",
    category: "Javascript",
    typeOfWork: "Full-time",
    experience: "Mid",
    employmentType: "Permanent",
    operatingMode: "Remote",
    onlineInterview: true,
    friendlyOffer: true,
    techStack: [
      { techLabel: "C++", level: 3 },
      { techLabel: "JavaScript", level: 2 },
      { techLabel: "C", level: 4 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Backend Developer",
    companyName: "Microsoft",
    locations: ["Kraków", "Gdańsk"],
    salary: {
      isUndisclosed: false,
      from: 18000,
      to: 24000,
      currency: "PLN",
    },
    datePosted: "02/08/2024",
    category: "Backend Development",
    typeOfWork: "Full-time",
    experience: "Senior",
    employmentType: "Permanent",
    operatingMode: "Hybrid",
    onlineInterview: true,
    friendlyOffer: true,
    techStack: [
      { techLabel: "Python", level: 4 },
      { techLabel: "Java", level: 3 },
      { techLabel: "SQL", level: 4 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Frontend Developer",
    companyName: "Facebook",
    locations: ["Poznań"],
    salary: {
      isUndisclosed: true,
      from: 0,
      to: 0,
      currency: "PLN",
    },
    datePosted: "28/07/2024",
    category: "Frontend Development",
    typeOfWork: "Part-time",
    experience: "Mid",
    employmentType: "B2B",
    operatingMode: "Remote",
    onlineInterview: true,
    friendlyOffer: false,
    techStack: [
      { techLabel: "JavaScript", level: 3 },
      { techLabel: "React", level: 3 },
      { techLabel: "HTML", level: 4 },
      { techLabel: "CSS", level: 4 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Data Scientist",
    companyName: "Amazon",
    locations: ["Wrocław", "Łódź"],
    salary: {
      isUndisclosed: false,
      from: 22000,
      to: 30000,
      currency: "PLN",
    },
    datePosted: "20/07/2024",
    category: "Data Science",
    typeOfWork: "Full-time",
    experience: "Mid",
    employmentType: "Permanent",
    operatingMode: "Remote",
    onlineInterview: false,
    friendlyOffer: true,
    techStack: [
      { techLabel: "Python", level: 4 },
      { techLabel: "R", level: 3 },
      { techLabel: "SQL", level: 4 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Mobile App Developer",
    companyName: "Spotify",
    locations: ["Warszawa", "Kraków"],
    salary: {
      isUndisclosed: false,
      from: 16000,
      to: 22000,
      currency: "PLN",
    },
    datePosted: "15/07/2024",
    category: "Mobile Development",
    typeOfWork: "Full-time",
    experience: "Junior",
    employmentType: "Specific-task contract",
    operatingMode: "Hybrid",
    onlineInterview: true,
    friendlyOffer: false,
    techStack: [
      { techLabel: "Kotlin", level: 3 },
      { techLabel: "Swift", level: 2 },
      { techLabel: "Java", level: 3 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "DevOps Engineer",
    companyName: "Oracle",
    locations: ["Gdynia", "Szczecin"],
    salary: {
      isUndisclosed: true,
      from: 0,
      to: 0,
      currency: "PLN",
    },
    datePosted: "10/07/2024",
    category: "DevOps",
    typeOfWork: "Freelance",
    experience: "Senior",
    employmentType: "Mandate contract",
    operatingMode: "Remote",
    onlineInterview: false,
    friendlyOffer: false,
    techStack: [
      { techLabel: "Bash", level: 4 },
      { techLabel: "Python", level: 3 },
      { techLabel: "Docker", level: 3 },
      { techLabel: "Kubernetes", level: 4 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "UX Designer",
    companyName: "Adobe",
    locations: ["Lublin", "Katowice"],
    salary: {
      isUndisclosed: false,
      from: 14000,
      to: 20000,
      currency: "PLN",
    },
    datePosted: "05/07/2024",
    category: "Design",
    typeOfWork: "Full-time",
    experience: "Mid",
    employmentType: "Permanent",
    operatingMode: "Hybrid",
    onlineInterview: true,
    friendlyOffer: true,
    techStack: [
      { techLabel: "Sketch", level: 4 },
      { techLabel: "Figma", level: 3 },
      { techLabel: "Adobe XD", level: 3 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Systems Analyst",
    companyName: "Intel",
    locations: ["Bydgoszcz"],
    salary: {
      isUndisclosed: true,
      from: 0,
      to: 0,
      currency: "PLN",
    },
    datePosted: "28/06/2024",
    category: "Systems Analysis",
    typeOfWork: "Full-time",
    experience: "Mid",
    employmentType: "Permanent",
    operatingMode: "Remote",
    onlineInterview: false,
    friendlyOffer: false,
    techStack: [
      { techLabel: "SQL", level: 4 },
      { techLabel: "Java", level: 3 },
      { techLabel: "Python", level: 3 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Cybersecurity Specialist",
    companyName: "IBM",
    locations: ["Zielona Góra", "Rzeszów"],
    salary: {
      isUndisclosed: false,
      from: 19000,
      to: 26000,
      currency: "PLN",
    },
    datePosted: "20/06/2024",
    category: "Cybersecurity",
    typeOfWork: "Full-time",
    experience: "Senior",
    employmentType: "B2B",
    operatingMode: "Hybrid",
    onlineInterview: true,
    friendlyOffer: true,
    techStack: [
      { techLabel: "Python", level: 4 },
      { techLabel: "JavaScript", level: 3 },
      { techLabel: "C++", level: 4 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "IT Support Specialist",
    companyName: "HP",
    locations: ["Warszawa"],
    salary: {
      isUndisclosed: false,
      from: 8000,
      to: 12000,
      currency: "PLN",
    },
    datePosted: "15/06/2024",
    category: "IT Support",
    typeOfWork: "Practice / Internship",
    experience: "Junior",
    employmentType: "Internship",
    operatingMode: "Remote",
    onlineInterview: false,
    friendlyOffer: false,
    techStack: [
      { techLabel: "Windows", level: 3 },
      { techLabel: "Linux", level: 2 },
      { techLabel: "Networking", level: 3 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Product Manager",
    companyName: "Asana",
    locations: ["Sopot", "Toruń"],
    salary: {
      isUndisclosed: true,
      from: 0,
      to: 0,
      currency: "PLN",
    },
    datePosted: "10/06/2024",
    category: "Product Management",
    typeOfWork: "Freelance",
    experience: "C-level",
    employmentType: "Specific-task contract",
    operatingMode: "Hybrid",
    onlineInterview: true,
    friendlyOffer: true,
    techStack: [
      { techLabel: "Agile", level: 4 },
      { techLabel: "Scrum", level: 3 },
      { techLabel: "Kanban", level: 2 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "AI Research Scientist",
    companyName: "DeepMind",
    locations: ["Warszawa", "Gdańsk"],
    salary: {
      isUndisclosed: false,
      from: 25000,
      to: 35000,
      currency: "PLN",
    },
    datePosted: "01/08/2024",
    category: "Artificial Intelligence",
    typeOfWork: "Full-time",
    experience: "Senior",
    employmentType: "Permanent",
    operatingMode: "Remote",
    onlineInterview: true,
    friendlyOffer: true,
    techStack: [
      { techLabel: "Python", level: 4 },
      { techLabel: "TensorFlow", level: 3 },
      { techLabel: "PyTorch", level: 4 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Blockchain Developer",
    companyName: "Ripple",
    locations: ["Kraków"],
    salary: {
      isUndisclosed: true,
      from: 0,
      to: 0,
      currency: "PLN",
    },
    datePosted: "25/07/2024",
    category: "Blockchain",
    typeOfWork: "Full-time",
    experience: "Mid",
    employmentType: "B2B",
    operatingMode: "Hybrid",
    onlineInterview: true,
    friendlyOffer: false,
    techStack: [
      { techLabel: "Solidity", level: 3 },
      { techLabel: "Go", level: 3 },
      { techLabel: "Rust", level: 3 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Machine Learning Engineer",
    companyName: "OpenAI",
    locations: ["Poznań", "Wrocław"],
    salary: {
      isUndisclosed: false,
      from: 23000,
      to: 32000,
      currency: "PLN",
    },
    datePosted: "20/07/2024",
    category: "Machine Learning",
    typeOfWork: "Full-time",
    experience: "Senior",
    employmentType: "Permanent",
    operatingMode: "Remote",
    onlineInterview: false,
    friendlyOffer: true,
    techStack: [
      { techLabel: "Python", level: 4 },
      { techLabel: "R", level: 3 },
      { techLabel: "Scala", level: 4 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Game Developer",
    companyName: "CD Projekt Red",
    locations: ["Warszawa", "Łódź"],
    salary: {
      isUndisclosed: false,
      from: 18000,
      to: 24000,
      currency: "PLN",
    },
    datePosted: "15/07/2024",
    category: "Game Development",
    typeOfWork: "Full-time",
    experience: "Mid",
    employmentType: "Specific-task contract",
    operatingMode: "Hybrid",
    onlineInterview: true,
    friendlyOffer: true,
    techStack: [
      { techLabel: "C++", level: 4 },
      { techLabel: "Unreal Engine", level: 3 },
      { techLabel: "Blueprints", level: 3 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "IT Consultant",
    companyName: "Accenture",
    locations: ["Gdynia", "Szczecin"],
    salary: {
      isUndisclosed: true,
      from: 0,
      to: 0,
      currency: "PLN",
    },
    datePosted: "10/07/2024",
    category: "Consulting",
    typeOfWork: "Freelance",
    experience: "Senior",
    employmentType: "Mandate contract",
    operatingMode: "Remote",
    onlineInterview: false,
    friendlyOffer: false,
    techStack: [
      { techLabel: "SQL", level: 4 },
      { techLabel: "SAP", level: 3 },
      { techLabel: "Oracle", level: 3 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Marketing Specialist",
    companyName: "HubSpot",
    locations: ["Lublin", "Katowice"],
    salary: {
      isUndisclosed: false,
      from: 12000,
      to: 18000,
      currency: "PLN",
    },
    datePosted: "05/07/2024",
    category: "Marketing",
    typeOfWork: "Full-time",
    experience: "Mid",
    employmentType: "Permanent",
    operatingMode: "Hybrid",
    onlineInterview: true,
    friendlyOffer: true,
    techStack: [
      { techLabel: "SEO", level: 4 },
      { techLabel: "Google Analytics", level: 2 },
      { techLabel: "Content Marketing", level: 3 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Network Engineer",
    companyName: "Cisco",
    locations: ["Bydgoszcz"],
    salary: {
      isUndisclosed: true,
      from: 0,
      to: 0,
      currency: "PLN",
    },
    datePosted: "28/06/2024",
    category: "Networking",
    typeOfWork: "Full-time",
    experience: "Senior",
    employmentType: "Permanent",
    operatingMode: "Remote",
    onlineInterview: false,
    friendlyOffer: false,
    techStack: [
      { techLabel: "Networking", level: 4 },
      { techLabel: "Cisco IOS", level: 4 },
      { techLabel: "Python", level: 3 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Data Analyst",
    companyName: "Spotify",
    locations: ["Zielona Góra", "Rzeszów"],
    salary: {
      isUndisclosed: false,
      from: 17000,
      to: 23000,
      currency: "PLN",
    },
    datePosted: "20/06/2024",
    category: "Data Analysis",
    typeOfWork: "Full-time",
    experience: "Mid",
    employmentType: "B2B",
    operatingMode: "Hybrid",
    onlineInterview: true,
    friendlyOffer: true,
    techStack: [
      { techLabel: "SQL", level: 4 },
      { techLabel: "Excel", level: 1 },
      { techLabel: "Python", level: 3 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Technical Writer",
    companyName: "Microsoft",
    locations: ["Warszawa"],
    salary: {
      isUndisclosed: false,
      from: 10000,
      to: 14000,
      currency: "PLN",
    },
    datePosted: "15/06/2024",
    category: "Technical Writing",
    typeOfWork: "Practice / Internship",
    experience: "Junior",
    employmentType: "Internship",
    operatingMode: "Remote",
    onlineInterview: false,
    friendlyOffer: false,
    techStack: [
      { techLabel: "Markdown", level: 3 },
      { techLabel: "HTML", level: 2 },
      { techLabel: "CSS", level: 2 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Cloud Solutions Architect",
    companyName: "Google Cloud",
    locations: ["Sopot", "Toruń"],
    salary: {
      isUndisclosed: true,
      from: 0,
      to: 0,
      currency: "PLN",
    },
    datePosted: "10/06/2024",
    category: "Cloud Computing",
    typeOfWork: "Freelance",
    experience: "C-level",
    employmentType: "Specific-task contract",
    operatingMode: "Hybrid",
    onlineInterview: true,
    friendlyOffer: true,
    techStack: [
      { techLabel: "AWS", level: 4 },
      { techLabel: "Azure", level: 4 },
      { techLabel: "GCP", level: 4 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "JavaScript Developer",
    companyName: "CodeWizards",
    locations: ["Warszawa", "Poznań"],
    salary: {
      isUndisclosed: false,
      from: 15000,
      to: 20000,
      currency: "PLN",
    },
    datePosted: "01/08/2024",
    category: "JavaScript Development",
    typeOfWork: "Full-time",
    experience: "Mid",
    employmentType: "Permanent",
    operatingMode: "Hybrid",
    onlineInterview: true,
    friendlyOffer: true,
    techStack: [
      { techLabel: "JavaScript", level: 4 },
      { techLabel: "React", level: 3 },
      { techLabel: "Node.js", level: 4 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "PHP Developer",
    companyName: "WebSmiths",
    locations: ["Gdańsk"],
    salary: {
      isUndisclosed: true,
      from: 0,
      to: 0,
      currency: "PLN",
    },
    datePosted: "25/07/2024",
    category: "PHP Development",
    typeOfWork: "Full-time",
    experience: "Senior",
    employmentType: "B2B",
    operatingMode: "Remote",
    onlineInterview: true,
    friendlyOffer: false,
    techStack: [
      { techLabel: "PHP", level: 4 },
      { techLabel: "Laravel", level: 3 },
      { techLabel: "MySQL", level: 4 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Java Developer",
    companyName: "Javatech Solutions",
    locations: ["Wrocław", "Łódź"],
    salary: {
      isUndisclosed: false,
      from: 18000,
      to: 25000,
      currency: "PLN",
    },
    datePosted: "20/07/2024",
    category: "Java Development",
    typeOfWork: "Full-time",
    experience: "Mid",
    employmentType: "Permanent",
    operatingMode: "Hybrid",
    onlineInterview: false,
    friendlyOffer: true,
    techStack: [
      { techLabel: "Java", level: 4 },
      { techLabel: "Spring", level: 3 },
      { techLabel: "Hibernate", level: 4 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: ".NET Developer",
    companyName: "DotNet Masters",
    locations: ["Warszawa", "Kraków"],
    salary: {
      isUndisclosed: false,
      from: 17000,
      to: 23000,
      currency: "PLN",
    },
    datePosted: "15/07/2024",
    category: ".NET Development",
    typeOfWork: "Full-time",
    experience: "Senior",
    employmentType: "Specific-task contract",
    operatingMode: "Remote",
    onlineInterview: true,
    friendlyOffer: false,
    techStack: [
      { techLabel: ".NET", level: 4 },
      { techLabel: "C#", level: 4 },
      { techLabel: "Azure", level: 3 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "QA Engineer",
    companyName: "Testify Inc.",
    locations: ["Gdynia", "Szczecin"],
    salary: {
      isUndisclosed: true,
      from: 0,
      to: 0,
      currency: "PLN",
    },
    datePosted: "10/07/2024",
    category: "Quality Assurance",
    typeOfWork: "Freelance",
    experience: "Mid",
    employmentType: "Mandate contract",
    operatingMode: "Remote",
    onlineInterview: false,
    friendlyOffer: false,
    techStack: [
      { techLabel: "Selenium", level: 3 },
      { techLabel: "JUnit", level: 3 },
      { techLabel: "Cypress", level: 3 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Automation Tester",
    companyName: "BugBusters",
    locations: ["Lublin", "Katowice"],
    salary: {
      isUndisclosed: false,
      from: 14000,
      to: 20000,
      currency: "PLN",
    },
    datePosted: "05/07/2024",
    category: "Testing",
    typeOfWork: "Full-time",
    experience: "Mid",
    employmentType: "Permanent",
    operatingMode: "Hybrid",
    onlineInterview: true,
    friendlyOffer: true,
    techStack: [
      { techLabel: "Java", level: 4 },
      { techLabel: "Selenium", level: 3 },
      { techLabel: "Postman", level: 3 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Full-Stack Developer",
    companyName: "DevFusion",
    locations: ["Bydgoszcz"],
    salary: {
      isUndisclosed: true,
      from: 0,
      to: 0,
      currency: "PLN",
    },
    datePosted: "28/06/2024",
    category: "Full-Stack Development",
    typeOfWork: "Full-time",
    experience: "Senior",
    employmentType: "Permanent",
    operatingMode: "Remote",
    onlineInterview: false,
    friendlyOffer: false,
    techStack: [
      { techLabel: "JavaScript", level: 4 },
      { techLabel: "PHP", level: 4 },
      { techLabel: "SQL", level: 3 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "JavaScript Tester",
    companyName: "CodeGuardians",
    locations: ["Zielona Góra", "Rzeszów"],
    salary: {
      isUndisclosed: false,
      from: 12000,
      to: 16000,
      currency: "PLN",
    },
    datePosted: "20/06/2024",
    category: "Testing",
    typeOfWork: "Full-time",
    experience: "Junior",
    employmentType: "B2B",
    operatingMode: "Hybrid",
    onlineInterview: true,
    friendlyOffer: true,
    techStack: [
      { techLabel: "JavaScript", level: 3 },
      { techLabel: "Mocha", level: 2 },
      { techLabel: "Chai", level: 2 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Senior PHP Developer",
    companyName: "HyperWeb",
    locations: ["Warszawa"],
    salary: {
      isUndisclosed: false,
      from: 20000,
      to: 26000,
      currency: "PLN",
    },
    datePosted: "15/06/2024",
    category: "PHP Development",
    typeOfWork: "Practice / Internship",
    experience: "Senior",
    employmentType: "Internship",
    operatingMode: "Remote",
    onlineInterview: false,
    friendlyOffer: false,
    techStack: [
      { techLabel: "PHP", level: 4 },
      { techLabel: "Symfony", level: 3 },
      { techLabel: "MySQL", level: 3 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
  {
    companyLogo: "/assets/companyLogo.webp",
    jobTitle: "Manual Tester",
    companyName: "SoftShield",
    locations: ["Sopot", "Toruń"],
    salary: {
      isUndisclosed: true,
      from: 0,
      to: 0,
      currency: "PLN",
    },
    datePosted: "10/06/2024",
    category: "Quality Assurance",
    typeOfWork: "Freelance",
    experience: "Mid",
    employmentType: "Specific-task contract",
    operatingMode: "Hybrid",
    onlineInterview: true,
    friendlyOffer: true,
    techStack: [
      { techLabel: "Manual Testing", level: 4 },
      { techLabel: "TestRail", level: 3 },
      { techLabel: "JIRA", level: 3 },
    ],
    jobDescription: `<h3>About us</h3><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p><h3>Job requirements:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul></p><h3>Benefits:</h3><ul><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li><li>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet</li></ul>`,
  },
];
